#!/usr/bin/env python3
"""Gera o bootstrap reproduzível do Control-plane, sem participar do pacote Client."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MIGRATIONS = ROOT / "migrations"
MAP = ROOT / "baseline-snapshot" / "tools" / "migration-destinations.json"
VERSION = ROOT / "baseline-snapshot" / "tools" / "delta_version.txt"
CONVERGENCE = ROOT / "master" / "001_control_plane_convergence_v1_4_3.sql"
RECONCILIATION = ROOT / "master" / "002_legacy_migration_reconciliation.sql"
OUT = ROOT / "master" / "bootstrap-control-plane.sql"
METADATA = ROOT / "master" / "bootstrap-control-plane.json"
INSERT_BEFORE = "20260913230055_f50b7d0b-e5e5-4cc8-9ad0-ddcfd8104005.sql"
HEADER = """-- Generated by supabase/master/tools/build_master_bootstrap.py\n-- Control-plane only. Never include this file in the Client package.\n\n"""


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def build() -> tuple[str, str]:
    document = json.loads(MAP.read_text(encoding="utf-8"))
    version_values = dict(
        line.split("=", 1)
        for line in VERSION.read_text(encoding="utf-8").splitlines()
        if "=" in line
    )
    release_version = version_values.get("version", "").strip()
    if not release_version:
        raise SystemExit("versão Master ausente em delta_version.txt")
    files = [entry["file"] for entry in document["migrations"] if entry["destination"] == "control-plane"]
    if len(files) != 28 or INSERT_BEFORE not in files:
        raise SystemExit("mapa Control-plane divergente do contrato auditado")
    parts = [HEADER]
    inserted = False
    for name in files:
        if name == INSERT_BEFORE:
            parts.extend(["-- MASTER CONVERGENCE\n", CONVERGENCE.read_text(encoding="utf-8").rstrip() + "\n\n"])
            parts.extend(["-- MASTER LEGACY RECONCILIATION\n", RECONCILIATION.read_text(encoding="utf-8").rstrip() + "\n\n"])
            inserted = True
        parts.extend([f"-- MIGRATION {name}\n", (MIGRATIONS / name).read_text(encoding="utf-8").rstrip() + "\n\n"])
    if not inserted:
        raise SystemExit("ponto de convergência Master ausente")
    bootstrap = "".join(parts)
    metadata = json.dumps(
        {
            "schemaVersion": 1,
            "releaseVersion": release_version,
            "controlPlaneMigrations": len(files),
            "convergenceFile": CONVERGENCE.name,
            "convergenceSha256": sha256(CONVERGENCE.read_bytes()),
            "reconciliationFile": RECONCILIATION.name,
            "reconciliationSha256": sha256(RECONCILIATION.read_bytes()),
            "bootstrapFile": OUT.name,
            "bootstrapSha256": sha256(bootstrap.encode()),
        },
        indent=2,
        sort_keys=True,
    ) + "\n"
    return bootstrap, metadata


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    bootstrap, metadata = build()
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != bootstrap:
            raise SystemExit("bootstrap Master ausente ou divergente; regenere antes da promoção")
        if not METADATA.is_file() or METADATA.read_text(encoding="utf-8") != metadata:
            raise SystemExit("metadados do bootstrap Master ausentes ou divergentes")
        print("bootstrap Master e metadados conferem")
        return
    OUT.write_text(bootstrap, encoding="utf-8")
    METADATA.write_text(metadata, encoding="utf-8")
    print(f"28 control-plane migrations + convergence -> {OUT}")

if __name__ == "__main__":
    main()
