/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app/notifications'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated/app/customers'
import { Route as AuthenticatedAppContentRouteImport } from './routes/_authenticated/app/content'
import { Route as AuthenticatedAppArenaRouteImport } from './routes/_authenticated/app/arena'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app/analytics'
import { Route as AuthenticatedAppCustomersIndexRouteImport } from './routes/_authenticated/app/customers.index'
import { Route as AuthenticatedAppSettingsAiRouteImport } from './routes/_authenticated/app/settings.ai'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppContentRoute = AuthenticatedAppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppArenaRoute = AuthenticatedAppArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppCustomersIndexRoute =
  AuthenticatedAppCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCustomersRoute,
  } as any)
const AuthenticatedAppSettingsAiRoute =
  AuthenticatedAppSettingsAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/portal/$token': typeof PortalTokenRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/arena': typeof AuthenticatedAppArenaRoute
  '/app/content': typeof AuthenticatedAppContentRoute
  '/app/customers': typeof AuthenticatedAppCustomersRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/settings/ai': typeof AuthenticatedAppSettingsAiRoute
  '/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/portal/$token': typeof PortalTokenRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/arena': typeof AuthenticatedAppArenaRoute
  '/app/content': typeof AuthenticatedAppContentRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/settings/ai': typeof AuthenticatedAppSettingsAiRoute
  '/app/customers': typeof AuthenticatedAppCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/portal/$token': typeof PortalTokenRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/arena': typeof AuthenticatedAppArenaRoute
  '/_authenticated/app/content': typeof AuthenticatedAppContentRoute
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRouteWithChildren
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/settings/ai': typeof AuthenticatedAppSettingsAiRoute
  '/_authenticated/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app'
    | '/portal/$token'
    | '/app/analytics'
    | '/app/arena'
    | '/app/content'
    | '/app/customers'
    | '/app/notifications'
    | '/app/settings'
    | '/app/'
    | '/app/settings/ai'
    | '/app/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/portal/$token'
    | '/app/analytics'
    | '/app/arena'
    | '/app/content'
    | '/app/notifications'
    | '/app/settings'
    | '/app'
    | '/app/settings/ai'
    | '/app/customers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/app'
    | '/portal/$token'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/arena'
    | '/_authenticated/app/content'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/settings/ai'
    | '/_authenticated/app/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/content': {
      id: '/_authenticated/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AuthenticatedAppContentRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/arena': {
      id: '/_authenticated/app/arena'
      path: '/arena'
      fullPath: '/app/arena'
      preLoaderRoute: typeof AuthenticatedAppArenaRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/customers/': {
      id: '/_authenticated/app/customers/'
      path: '/'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AuthenticatedAppCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAppCustomersRoute
    }
    '/_authenticated/app/settings/ai': {
      id: '/_authenticated/app/settings/ai'
      path: '/ai'
      fullPath: '/app/settings/ai'
      preLoaderRoute: typeof AuthenticatedAppSettingsAiRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
  }
}

interface AuthenticatedAppCustomersRouteChildren {
  AuthenticatedAppCustomersIndexRoute: typeof AuthenticatedAppCustomersIndexRoute
}

const AuthenticatedAppCustomersRouteChildren: AuthenticatedAppCustomersRouteChildren =
  {
    AuthenticatedAppCustomersIndexRoute: AuthenticatedAppCustomersIndexRoute,
  }

const AuthenticatedAppCustomersRouteWithChildren =
  AuthenticatedAppCustomersRoute._addFileChildren(
    AuthenticatedAppCustomersRouteChildren,
  )

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsAiRoute: typeof AuthenticatedAppSettingsAiRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsAiRoute: AuthenticatedAppSettingsAiRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppArenaRoute: typeof AuthenticatedAppArenaRoute
  AuthenticatedAppContentRoute: typeof AuthenticatedAppContentRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppArenaRoute: AuthenticatedAppArenaRoute,
  AuthenticatedAppContentRoute: AuthenticatedAppContentRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
