// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import {
  resolveSupabasePublicRuntimeConfig,
  SupabaseRuntimeConfigError,
} from "./runtime-config.server";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string, userToken?: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    // Force the end-user bearer to win over anything supabase-js injected
    // (e.g. `Authorization: Bearer <apikey>` for anon), so PostgREST RLS
    // evaluates `auth.uid()` as the signed-in user, not anon.
    if (userToken) {
      headers.set("Authorization", `Bearer ${userToken}`);
    }
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    let config;
    try {
      config = resolveSupabasePublicRuntimeConfig();
    } catch (error) {
      const detail =
        error instanceof SupabaseRuntimeConfigError
          ? error.missingOrInvalid.join(", ")
          : "unknown_configuration_error";
      console.error(`[Supabase] Invalid auth runtime configuration: ${detail}.`);
      throw new Error("Configuração de autenticação indisponível.");
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      throw new Error("Unauthorized: Invalid token");
    }

    const supabase = createClient<Database>(config.url, config.publishableKey, {
      global: {
        fetch: createSupabaseFetch(config.publishableKey, token),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    // `getClaims` valida o JWT localmente (JWKS). Em rotação de chaves ou
    // quando o JWKS ainda não está em cache no Worker, isso falha mesmo com um
    // token válido — nesse caso confirmamos no servidor de auth via getUser().
    const { data, error } = await supabase.auth.getClaims(token);
    let userId = data?.claims?.sub ?? null;
    let claims = data?.claims ?? null;

    if (error || !userId) {
      const { data: userData, error: userErr } = await supabase.auth.getUser(token);
      if (userErr || !userData?.user?.id) {
        throw new Error("Unauthorized: Invalid token");
      }
      userId = userData.user.id;
      claims = (claims ?? { sub: userId }) as typeof claims;
    }

    return next({
      context: {
        supabase,
        userId,
        claims: claims!,
      },
    });
  },
);
